apiVersion: v1
kind: Secret
metadata: 
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root
  MYSQL_USER: root
  MYSQL_DB_URL: mysql+pymysql://root:root@mysql-service:3306/demodb
  SECRET_KEY: "your-secret-key-change-in-production"
  JWT_SECRET_KEY: "your-jwt-secret-key-change-in-production"